version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node

    steps:
      - checkout

      - restore_cache:
          key: bourbon-io-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: bourbon-io-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: bourbon-io-npm-{{ arch }}-{{ checksum "package.json" }}

      - run:
          name: Install Node dependencies
          command: npm install

      - save_cache:
          key: bourbon-io-npm-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Setup the environment
          command: cp .env.sample .env

      - run:
          name: Build Middleman site
          command: bundle exec middleman build --verbose
