version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "stylelint*"
      - match:
          dependency_name: "eslint*"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
